service: packt-sample-lambda-api

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action: s3:*
      Resource: "*"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello/{name}
          method: get

  reads3:
    handler: handler.reads3
    events:
      - http:
          path: reads3
          method: get


